project:
  type: website

website:
  title: "(x)Ability Design Lab"
  site-url: "https://xabilitylab.ischool.illinois.edu/"
  repo-url: "https://github.com/xability/xability.github.io"
  issue-url: https://github.com/xability/xability.github.io/issues/new
  repo-actions: [edit, issue]
  image: "logo/logo_with_hue.jpeg"
  image-alt: "(x)Ability Design Lab"
  favicon: "logo/favicon.png"
  # google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  page-navigation: true
  bread-crumbs: true
  # search:
    # show-item-context: true
    # type: overlay
    # algolia:
      # index-name: prod_QUARTO
      # application-id: ZPJB5I1QN7
      # search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
      # analytics-events: true
      # show-logo: true

  page-footer:
    # left: |
      # Proudly supported by
      # [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center: '&copy; 2024 &middot; Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)'
    right:
      # - icon: twitter
        # href: https://twitter.com/quarto_pub
        # aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/xability
        aria-label: (x)Ability Design Lab GitHub
      # - icon: rss
        # href: https://quarto.org/docs/blog/index.xml
        # aria-label: Quarto Blog RSS

  navbar:
    logo: "logo/darkmode_with_hue.jpeg"
    logo-alt: "(x)Ability Design Lab logo"
    title: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# bibliography: references.bib
