project:
  type: website

website:
  title: "(x)Ability Design Lab"
  site-url: "https://xabilitylab.ischool.illinois.edu/"
  repo-url: "https://github.com/xability/xability.github.io"
  issue-url: https://github.com/xability/xability.github.io/issues/new
  repo-actions: [edit, issue]
  image: "logo/logo_with_hue.jpeg"
  favicon: "logo/favicon.png"
  # google-analytics: "G-FV9Z7SDZ0M"
  # open-graph: true

  page-footer:
    # left: |
      # Proudly supported by
      # [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center: '&copy; 2024 &middot; Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)'
    right:
      # - icon: twitter
        # href: https://twitter.com/quarto_pub
        # aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/xability
        aria-label: (x)Ability Design Lab GitHub
      # - icon: rss
        # href: https://quarto.org/docs/blog/index.xml
        # aria-label: Quarto Blog RSS

  navbar:
    logo: "logo/logo_without_hue.jpeg"
    logo-alt: "(x)Ability Design Lab logo"
    title: false
    href: https://xabilitylab.ischool.illinois.edu/
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



